import React from 'react';
import { ReceiptData, Person } from '../types';
import { Share2, Smartphone, AlertCircle } from 'lucide-react';
import { PieChart, Pie, Cell, Tooltip, ResponsiveContainer, Legend } from 'recharts';

interface Props {
  receiptData: ReceiptData;
  people: Person[];
  hostId: string;
}

export const Summary: React.FC<Props> = ({ receiptData, people, hostId }) => {
  
  // Calculate Splits
  const calculateShare = (personId: string) => {
    let mySubtotal = 0;
    
    receiptData.items.forEach(item => {
      if (item.assignedTo.includes(personId)) {
        mySubtotal += item.price / item.assignedTo.length;
      }
    });

    // Pro-rate tax and service charge based on share of subtotal
    // Note: If no one claimed items, subtotal might be 0, avoid div by 0
    const ratio = receiptData.subtotal > 0 ? mySubtotal / receiptData.subtotal : 0;
    const myService = receiptData.serviceCharge * ratio;
    const myGst = receiptData.gst * ratio;
    
    return {
      subtotal: mySubtotal,
      tax: myGst,
      service: myService,
      total: mySubtotal + myService + myGst
    };
  };

  const shares = people.map(p => ({
    ...p,
    share: calculateShare(p.id)
  }));

  const activeShares = shares.filter(p => p.share.total > 0.01);

  // Validation
  const totalCalculated = activeShares.reduce((sum, p) => sum + p.share.total, 0);
  const unassignedAmount = receiptData.total - totalCalculated;
  const isFullyAssigned = Math.abs(unassignedAmount) < 0.05;

  const chartData = activeShares.map(p => ({
    name: p.name,
    value: parseFloat(p.share.total.toFixed(2)),
    color: p.color
  }));

  const generateWhatsAppLink = () => {
    const host = people.find(p => p.id === hostId);
    let text = `🧾 *Bill Split: ${receiptData.merchantName}*\n\n`;
    text += `Total Bill: SGD ${receiptData.total.toFixed(2)}\n\n`;
    
    activeShares.forEach(p => {
        if (p.id !== hostId) {
            text += `🔹 *${p.name}*: $${p.share.total.toFixed(2)}\n`;
        }
    });
    
    if (host) {
        text += `\n📲 PayNow to ${host.name} (Check group for number)\n`;
    }
    
    text += `\n_Generated by Splitlah_`;
    
    return `https://wa.me/?text=${encodeURIComponent(text)}`;
  };

  return (
    <div className="space-y-6">
       
       {/* Total Header */}
       <div className="bg-white rounded-xl shadow-sm border border-slate-200 p-6 flex flex-col items-center justify-center">
            <span className="text-sm font-medium text-slate-500 uppercase tracking-wider">Total Bill</span>
            <h2 className="text-4xl font-bold text-slate-900 mt-2">
                ${receiptData.total.toFixed(2)}
            </h2>
            <p className="text-slate-400 text-sm mt-1 font-medium">
                {receiptData.merchantName}
            </p>
       </div>

       {/* Chart */}
       <div className="h-64 w-full bg-white rounded-xl shadow-sm border border-slate-200 p-4">
            <ResponsiveContainer width="100%" height="100%">
                <PieChart>
                    <Pie
                        data={chartData}
                        innerRadius={60}
                        outerRadius={80}
                        paddingAngle={5}
                        dataKey="value"
                    >
                        {chartData.map((entry, index) => (
                            <Cell key={`cell-${index}`} fill={entry.color} />
                        ))}
                    </Pie>
                    <Tooltip formatter={(value: number) => `$${value.toFixed(2)}`} />
                    <Legend />
                </PieChart>
            </ResponsiveContainer>
       </div>

       {/* Detailed Breakdown */}
       <div className="bg-white rounded-xl shadow-sm border border-slate-200 overflow-hidden">
            <div className="bg-slate-50 px-4 py-3 border-b border-slate-200">
                <h3 className="font-semibold text-slate-800">Payment Breakdown</h3>
            </div>
            <div className="divide-y divide-slate-100">
                {activeShares.map(person => (
                    <div key={person.id} className="p-4 flex justify-between items-center">
                        <div className="flex items-center gap-3">
                            <div className="w-10 h-10 rounded-full flex items-center justify-center text-white font-bold" style={{ backgroundColor: person.color }}>
                                {person.name.substring(0, 1)}
                            </div>
                            <div>
                                <p className="font-medium text-slate-900">{person.name} {person.id === hostId && '(You)'}</p>
                                <p className="text-xs text-slate-500">
                                    ${person.share.subtotal.toFixed(2)} + ${ (person.share.tax + person.share.service).toFixed(2) } fees
                                </p>
                            </div>
                        </div>
                        <div className="text-right">
                            <span className="block text-lg font-bold text-slate-800">${person.share.total.toFixed(2)}</span>
                        </div>
                    </div>
                ))}
            </div>
            
            {/* Total Check Row */}
            <div className={`p-4 bg-slate-50 border-t border-slate-200 flex justify-between items-center ${!isFullyAssigned ? 'bg-red-50' : ''}`}>
                <span className="font-bold text-slate-700">Total Collected</span>
                <div className="text-right">
                    <span className={`block text-xl font-bold ${!isFullyAssigned ? 'text-red-600' : 'text-slate-900'}`}>
                        ${totalCalculated.toFixed(2)}
                    </span>
                    {!isFullyAssigned && (
                         <span className="text-xs text-red-500 font-medium">Target: ${receiptData.total.toFixed(2)}</span>
                    )}
                </div>
            </div>
            
            {!isFullyAssigned && (
                <div className="p-3 bg-red-100 text-red-700 text-xs flex items-center gap-2">
                    <AlertCircle size={16} />
                    <span>${unassignedAmount.toFixed(2)} is currently unassigned. Please go back and assign items to ensure the bill is fully covered.</span>
                </div>
            )}
       </div>

        {/* Regulatory / disclaimer */}
       <div className="p-3 bg-blue-50 text-blue-800 text-xs rounded-lg">
            <strong>Note:</strong> This app calculates splits based on 9% GST and 10% Service Charge ratios. Please verify the final PayNow transfer amounts with your banking app (e.g., Standard Chartered, DBS, UOB).
       </div>

       {/* Actions */}
       <div className="grid grid-cols-2 gap-4">
            <a 
                href={generateWhatsAppLink()}
                target="_blank"
                rel="noreferrer"
                className="flex items-center justify-center gap-2 bg-[#25D366] text-white py-3 px-4 rounded-xl font-semibold hover:bg-[#128C7E] transition-colors shadow-sm"
            >
                <Share2 size={18} />
                WhatsApp
            </a>
            <button className="flex items-center justify-center gap-2 bg-slate-800 text-white py-3 px-4 rounded-xl font-semibold hover:bg-slate-900 transition-colors shadow-sm">
                <Smartphone size={18} />
                Show PayNow QR
            </button>
       </div>
    </div>
  );
};